# -*- coding: utf-8 -*-
# Dias 23/11 a 03/12 e pendências

DIAS_B = [
 {"d":"23","m":"nov","sem":"Seg","c":"Florianópolis","r":"Praias do leste e pôr do sol açoriano","i":[
   {"mv":"25 min|Uber|Novotel → Praia Mole|09:00"},
   {"h":"09:25","k":"passeio","g":"2h","t":"Praia Mole",
    "x":"Areia clara e morros dos dois lados. Mar forte, é praia de olhar mais do que de entrar.",
    "av":"Segunda de manhã é o horário mais vazio da semana nas praias do leste."},
   {"mv":"10 min|Uber|Praia Mole → Praia da Joaquina|11:25"},
   {"h":"11:35","k":"passeio","g":"1h15","t":"Praia da Joaquina",
    "x":"A 10 min da Mole. Vale pelas dunas e pelo mirante da entrada, mesmo sem descer à areia."},
   {"mv":"10 min|Uber|Joaquina → Lagoa da Conceição|12:50"},
   {"h":"13:00","k":"jantar","g":"1h15","t":"Almoço na Lagoa",
    "x":"Parada só para comer, no caminho de volta. As praias não têm boa estrutura de restaurante e a Lagoa fica a 10 min da Joaquina."},
   {"mv":"25 min|Uber|Lagoa da Conceição → Novotel|14:15"},
   {"h":"14:40","k":"livre","g":"2h","t":"Descanso no Novotel",
    "x":"Duas horas deitado antes de sair para o pôr do sol. O dia termina tarde e o jantar é longe do hotel."},
   {"mv":"25 min|Uber|Novotel → Santo Antônio de Lisboa|16:45"},
   {"h":"17:10","k":"passeio","g":"2h15","t":"Santo Antônio de Lisboa",
    "x":"Vilarejo açoriano com o melhor pôr do sol da ilha. O sol se põe às 18:50 em novembro."},
   {"mv":"5 min|A pé|Centrinho de Santo Antônio → restaurante|19:25"},
   {"h":"19:30","k":"jantar","g":"Jantar decidido","t":"Restaurante Chão Batido",
    "x":"Rua Quinze de Novembro 103, Santo Antônio de Lisboa. Frutos do mar com vista da baía, no próprio vilarejo do pôr do sol.",
    "cod":"+55 48 3235-2186","cl":"Telefone",
    "av":"Confirme por telefone se abre na segunda. Se estiver fechado, volte ao centro: a Trattoria Carbone e o Mercado Público ficam a 25 min de Uber daqui."},
   {"mv":"25 min|Uber|Santo Antônio de Lisboa → Novotel|21:00"},
   {"h":"21:25","k":"livre","t":"Última noite em Floripa",
    "x":"A mala se arruma amanhã de manhã, sem pressa. O check-out é ao meio-dia e o ônibus para Curitiba só sai às 12:45."}
 ]},

 {"d":"24","m":"nov","sem":"Ter","c":"Florianópolis → Curitiba","r":"Cinco horas de estrada, de dia, e chegada ao centro","i":[
   {"h":"—","k":"livre","g":"Manhã","t":"Manhã livre na Beira Mar",
    "x":"Café no hotel, uma última caminhada na orla e a mala fechada com calma. O check-out é só ao meio-dia."},
   {"mv":"5 min|A pé|Novotel → restaurantes da orla|10:25"},
   {"h":"10:30","k":"jantar","g":"1h","t":"Almoço cedo na Beira Mar",
    "x":"Coma antes de embarcar. O ônibus sai 12:45 e vocês só chegam em Curitiba às 19:00."},
   {"h":"12:00","k":"hotel","g":"Check-out","t":"Novotel Florianópolis",
    "x":"Check-out no horário. A rodoviária fica a 15 min.","cod":"6172.585.897 · PIN 3972","cl":"Reserva"},
   {"mv":"15 min|Uber|Novotel → Rodoviária de Florianópolis|12:15"},
   {"h":"12:45","k":"onibus","g":"Penha","t":"Florianópolis → Curitiba",
    "x":"Plataforma VIP Penha. Cama. Rafa poltrona 53, mãe poltrona 52. Chegada por volta das 19:00.",
    "cod":"Rafa 010335300370 · Mãe 010335300375","cl":"Bilhetes",
    "av":"Viagem diurna, cinco horas pela BR-101, a única do roteiro com paisagem. Compre água e algo para comer na rodoviária antes de embarcar."},
   {"mv":"12 min|Uber|Rodoferroviária → Novotel, no centro|19:15"},
   {"h":"19:30","k":"hotel","g":"Check-in","t":"Novotel Curitiba Batel",
    "x":"Rua Doutor Pedrosa 288, Centro. Cinco noites, café incluído. Apesar do nome, o hotel fica no centro, a quatro minutos a pé da Rua 24 Horas.",
    "cod":"a preencher","cl":"Reserva",
    "av":"Ponha aqui o código da reserva do Novotel antes de viajar."},
   {"mv":"12 min|Uber|Novotel → Rua Bpo. Dom José|20:18"},
   {"h":"20:30","k":"jantar","g":"Jantar decidido","t":"Taco El Pancho",
    "x":"Rua Bpo. Dom José 2293, Batel. Fajitas e tacos com música ao vivo. Terça até 01:00.",
    "cod":"+55 41 99759-6000","cl":"Telefone",
    "av":"Costuma lotar. Reserve por telefone quando chegar em Curitiba."}
 ]},

 {"d":"25","m":"nov","sem":"Qua","c":"Curitiba","r":"Jardim Botânico de manhã, Niemeyer à tarde","i":[
   {"h":"—","k":"livre","g":"Manhã","t":"Café da manhã no Novotel","x":"Café incluído. Saiam por volta das 09:15."},
   {"mv":"12 min|Uber|Novotel → Jardim Botânico|09:18"},
   {"h":"09:30","k":"passeio","g":"2h30","t":"Jardim Botânico",
    "x":"Abre às 06:00. A estufa de vidro, o jardim francês e a trilha do bosque."},
   {"mv":"12 min|Uber|Jardim Botânico → centro|12:18"},
   {"h":"12:30","k":"jantar","g":"1h15","t":"Almoço","x":"Coma antes do museu."},
   {"mv":"8 min|Uber|Almoço → Museu Oscar Niemeyer|13:52"},
   {"h":"14:00","k":"passeio","g":"2h","t":"Museu Oscar Niemeyer",
    "x":"O Olho e o anexo. Fecha às segundas, quarta é dia tranquilo."},
   {"mv":"8 min|Uber|Museu Oscar Niemeyer → Novotel|16:22"},
   {"h":"16:30","k":"livre","g":"Descanso","t":"Volta ao Novotel","x":"Banho e uma hora deitado antes do jantar."},
   {"mv":"12 min|Uber|Novotel → Água Verde|19:18"},
   {"h":"19:30","k":"jantar","g":"Jantar decidido","t":"Restaurante Ibérico",
    "x":"Av. Água Verde 588. Bacalhau, paella e flamenco em algumas noites. Quarta até 23:00.",
    "cod":"+55 41 99980-1003","cl":"Telefone"}
 ]},

 {"d":"26","m":"nov","sem":"Qui","c":"Curitiba","r":"Centro histórico de manhã, Expomotorhome à tarde","i":[
   {"mv":"7 min|Uber|Novotel → Mercado Municipal|08:53"},
   {"h":"09:00","k":"passeio","g":"1h30","t":"Mercado Municipal de Curitiba",
    "x":"Abre às 07:00 e fecha segunda. Boxes de frios, café e o setor orgânico. Bom lugar para o café da manhã reforçado."},
   {"mv":"8 min|A pé|Mercado Municipal → Rua XV|10:37"},
   {"h":"10:45","k":"passeio","g":"1h30","t":"Rua XV e Largo da Ordem",
    "x":"Calçadão, Boca Maldita e o casario do centro histórico. Tudo a pé, num raio de 15 min."},
   {"h":"12:30","k":"jantar","g":"1h","t":"Almoço no centro",
    "x":"Coma antes de subir para Pinhais. A feira não tem praça de alimentação garantida."},
   {"mv":"30 min|Uber|Centro → Expotrade, em Pinhais|13:30"},
   {"h":"14:00","k":"passeio","g":"6h · até 20:00","t":"10ª Expomotorhome",
    "x":"Expotrade Convention Center, Pinhais.","cod":"Pedido 3387368","cl":"Ingresso",
    "av":"Ingresso pessoal e intransferível, documento com foto. Leve fita métrica, fotografe a placa de cada modelo junto com o interior e pergunte a carga útil com os tanques cheios. Saiam por volta das 20:00."},
   {"mv":"30 min|Uber|Expotrade, Pinhais → centro|20:00"},
   {"h":"20:30","k":"jantar","t":"No Novotel",
    "x":"Vocês voltam da feira tarde e cansados. Coma no hotel e durma.",
    "av":"Se chegarem antes das 20:00 e com fome de restaurante, o Babilônia fica a 10 min e serve até meia-noite: +55 41 3082-6009."}
 ]},

 {"d":"27","m":"nov","sem":"Sex","c":"Curitiba → Morretes","r":"Litorina Luxo pela Serra do Mar. O passeio do roteiro","i":[
   {"h":"07:00","k":"via","g":"Apanhe","t":"Transfer no hotel",
    "x":"A partir das 07:00. Se não houver apanhe, apresentar 07:30 no Bloco C.","cod":"Reserva 189865","cl":"Reserva",
    "av":"Avise a Serra Verde do novo endereço. O apanhe estava registrado no Pestana, no Batel, e agora é no Novotel, na Rua Doutor Pedrosa 288."},
   {"h":"08:30","k":"passeio","g":"Serra Verde Express","t":"Litorina Luxo Copacabana → Morretes",
    "x":"Vagão 19, poltronas 9 e 10. Almoço com barreado, Hisgeopar e tour em Antonina. Retorno de van às 17:30.",
    "cod":"88958485 · 88958566","cl":"Vouchers"},
   {"h":"19:30","k":"jantar","t":"Leve, no Novotel",
    "x":"O almoço da Litorina é barreado, prato pesado, e vocês voltam de van às 17:30 cansados. Algo simples no hotel resolve."}
 ]},

 {"d":"28","m":"nov","sem":"Sáb","c":"Curitiba","r":"Tanguá, Ópera de Arame e Barigui, tudo no mesmo arco","i":[
   {"mv":"20 min|Uber|Novotel → Parque Tanguá|08:40"},
   {"h":"09:00","k":"passeio","g":"1h30","t":"Parque Tanguá",
    "x":"Mirante sobre a antiga pedreira, cascata e o túnel entre os dois lados. Sábado enche depois das 11:00, chegue cedo."},
   {"mv":"15 min|A pé|Parque Tanguá → Ópera de Arame|10:30"},
   {"h":"10:45","k":"passeio","g":"45 min","t":"Ópera de Arame",
    "x":"Fica ao lado do Tanguá, dá para ir a pé em 15 min. Estrutura tubular sobre um lago, visita rápida."},
   {"mv":"10 min|Uber|Ópera de Arame → Santa Felicidade|11:50"},
   {"h":"12:00","k":"jantar","g":"1h30","t":"Almoço em Santa Felicidade",
    "x":"Bairro italiano a 10 min da Ópera. Cantinas de rodízio de massa, prato típico de Curitiba."},
   {"mv":"10 min|Uber|Santa Felicidade → Parque Barigui|14:20"},
   {"h":"14:30","k":"passeio","g":"2h","t":"Parque Barigui",
    "x":"Capivaras, lago e área de caminhada plana. O parque mais fácil para a mãe andar sem subida."},
   {"mv":"15 min|Uber|Parque Barigui → Novotel|16:45"},
   {"h":"17:00","k":"livre","g":"Descanso","t":"Volta ao Novotel","x":"Banho e pausa antes do último jantar com a sua mãe."},
   {"mv":"12 min|Uber|Novotel → Água Verde|19:18"},
   {"h":"19:30","k":"jantar","g":"Jantar decidido","t":"Barolo Curitiba",
    "x":"Av. Silva Jardim 2487, Água Verde. Casa tradicional de Curitiba. Sábado das 19:00 à meia-noite. Porções grandes, feitas para dividir, então peça menos do que parece.",
    "cod":"+55 41 3243-3430","cl":"Telefone",
    "av":"Último jantar com a sua mãe. Reserve com antecedência, sábado enche."}
 ]},

 {"d":"29","m":"nov","sem":"Dom","c":"Curitiba · ENADE e separação","r":"Prova à tarde, mãe no shopping, dois ônibus à noite","i":[
   {"mv":"6 min|Uber|Novotel → Largo da Ordem|08:54"},
   {"h":"09:00","k":"passeio","g":"1h30","t":"Feira do Largo da Ordem",
    "x":"Só aos domingos, das 09:00 às 14:00. Vá com a mãe antes da prova, dá tempo folgado."},
   {"mv":"6 min|Uber|Largo da Ordem → Novotel|10:24"},
   {"h":"10:30","k":"jantar","g":"30 min","t":"Almoço cedo, antes da prova",
    "x":"Coma leve. A prova é longa e você não vai poder sair para comer."},
   {"h":"11:00","k":"via","g":"Rafa","t":"Sair para o local do ENADE",
    "x":"Leve documento com foto e caneta preta.",
    "av":"Confirme o endereço e o horário de fechamento dos portões no cartão de confirmação. Portão fechado não abre."},
   {"h":"11:00","k":"hotel","g":"Mãe","t":"Check-out do Novotel",
    "x":"Check-out até 12:00. As duas malas ficam no guarda-volumes do hotel.","cod":"a preencher","cl":"Reserva"},
   {"mv":"8 min|Uber|Novotel → Shopping Estação|11:52"},
   {"h":"12:00","k":"livre","g":"Mãe · tarde","t":"Shopping Estação",
    "x":"Av. Sete de Setembro 2775, a 8 min do hotel. Praça de alimentação, cinema e ar condicionado. Lugar seguro para passar a tarde e almoçar.",
    "av":"O ponto de espera mudou junto com o hotel. O Shopping Batel ficava ao lado do Pestana, e o Novotel está no centro."},
   {"h":"17:30","k":"via","g":"Encontro","t":"Shopping Estação",
    "x":"Combine um ponto fixo, não só o shopping. A praça de alimentação funciona bem.",
    "av":"Se a prova terminar depois das 18:00, mude o plano: a mãe pega as malas no Novotel e vai direto para a rodoferroviária, e você a encontra lá."},
   {"mv":"8 min|Uber|Shopping Estação → Novotel|18:22"},
   {"h":"18:30","k":"hotel","g":"Malas","t":"Buscar as malas no Novotel","x":"8 min de carro do shopping."},
   {"mv":"12 min|Uber|Novotel → Rodoferroviária|19:00"},
   {"h":"19:15","k":"via","g":"Chegada ao terminal","t":"Rodoferroviária de Curitiba",
    "x":"Av. Presidente Affonso Camargo 330. Localize a plataforma 16 antes de qualquer outra coisa."},
   {"h":"19:45","k":"onibus","g":"Satélite Norte · mãe","t":"Curitiba → Lins",
    "x":"Plataforma 16, poltrona 47, leito cama. Linha Goiânia–Florianópolis.","cod":"010021796905","cl":"Bilhete",
    "av":"Combine com seus irmãos quem busca ela na rodoviária de Lins na manhã do dia 30."},
   {"h":"20:00","k":"livre","g":"3h no terminal","t":"Jantar e espera na rodoferroviária",
    "x":"A praça de alimentação fica no piso superior do Bloco Estadual e funciona 24 horas. Estação Rodo é a melhor da casa: prato feito com bife bem servido sai perto de R$ 40 com refrigerante. Express Dom Bolinha fica ao lado, serve o mesmo cardápio e tem café coado na hora por uns R$ 5. O salão tem mesas, sofás e tomadas para carregar o celular.",
    "av":"Peça o cardápio completo, não só o que estiver na mesa. Há relato de duas versões diferentes, uma com pratos mais caros. Guarda-volumes funciona 24h com pix e cartão. Caixas eletrônicos ficam perto do desembarque."},
   {"h":"23:00","k":"onibus","g":"Penha · Rafa","t":"Curitiba → São Paulo",
    "x":"Portão J, poltrona 35, cama individual. Chega ao Tietê por volta das 05:30. Esteja no portão às 22:40.",
    "cod":"010323536305","cl":"Bilhete"}
 ]},

 {"d":"30","m":"nov","sem":"Seg","c":"São Paulo","r":"Manhã de sono, Pinacoteca e tarde livre","i":[
   {"h":"05:30","k":"via","g":"Chegada","t":"Rodoviária do Tietê","x":"Com mala, prefira carro pelo app."},
   {"mv":"20 min|Uber|Rodoviária do Tietê → Sooz, na República|05:55"},
   {"h":"06:15","k":"hotel","g":"Entrada","t":"Sooz Hotel Collection",
    "x":"Av. São Luís 234, República. Quarto reservado desde 29/11 para entrar de manhã. Durma até umas 10:00.",
    "cod":"6800.543.753 · PIN 1786","cl":"Reserva"},
   {"mv":"12 min|Uber|Sooz → Estação da Luz|11:18"},
   {"h":"11:30","k":"passeio","g":"2h","t":"Pinacoteca e Parque da Luz",
    "x":"A Pinacoteca fecha às terças, então hoje é o único dia possível.",
    "av":"Segunda o Museu do Ipiranga e o MASP estão fechados."},
   {"mv":"12 min|Uber|Luz → República|13:33"},
   {"h":"13:45","k":"jantar","g":"1h","t":"Almoço perto do hotel",
    "x":"Largo do Arouche e arredores têm mesa boa e barata a 5 min a pé."},
   {"mv":"10 min|Uber|República → Consolação|14:50"},
   {"h":"15:00","k":"passeio","g":"2h30","t":"Rua Frei Caneca",
    "x":"A rua gay de São Paulo, entre a Paulista e a Consolação. Shopping Frei Caneca, cafés e lojas. De tarde é tranquila, boa para andar sem pressa."},
   {"mv":"10 min|Uber|Frei Caneca → Sooz|17:50"},
   {"h":"18:00","k":"livre","g":"Descanso","t":"Banho e pausa",
    "x":"Você acordou às 05:00. Uma hora de sono aqui muda a noite."},
   {"mv":"5 min|A pé|Sooz → Largo do Arouche|19:55"},
   {"h":"20:00","k":"jantar","t":"Estrela do Arouche ou Virado-sp",
    "x":"Largo do Arouche 82 e 150. Os dois abrem segunda, são casuais e ficam a cinco minutos do hotel."},
   {"mv":"8 min|A pé|Largo do Arouche → Rua Bento Freitas|21:52"},
   {"h":"22:00","k":"livre","g":"Noite","t":"Dedalos Bar",
    "x":"Rua Bento Freitas 38, República. Aberto 24 horas, todos os dias. Levam documento com foto na porta.",
    "av":"O Wild Thermas, na Rua Dr. Veiga Filho 802 em Higienópolis, fecha às 23:00 na segunda. 10 min de Uber, só vale se você sair cedo."}
 ]},

 {"d":"01","m":"dez","sem":"Ter","c":"São Paulo","r":"Ipiranga, Ibirapuera e saída para o voo","i":[
   {"mv":"25 min|Uber|Sooz → Museu do Ipiranga|08:35"},
   {"h":"09:00","k":"passeio","g":"2h30","t":"Museu do Ipiranga",
    "x":"Entrada por horário marcado. O jardim antes do prédio já vale a caminhada.",
    "av":"Ingresso ainda não comprado. Monitorar o calendário em meados de outubro."},
   {"mv":"25 min|Uber|Ipiranga → Centro|12:05"},
   {"h":"12:30","k":"jantar","g":"1h","t":"Almoço",
    "x":"Coma bem. À noite você embarca e só janta no avião de madrugada."},
   {"mv":"20 min|Uber|Almoço → Parque Ibirapuera|13:40"},
   {"h":"14:00","k":"passeio","g":"2h","t":"Parque Ibirapuera",
    "x":"Plano, sombreado e enorme. Entre pelo Portão 10, ande até a Marquise e o lago. Se der vontade de museu, o MAC USP fica ali com terraço aberto."},
   {"mv":"20 min|Uber|Parque Ibirapuera → Sooz|16:40"},
   {"h":"17:00","k":"hotel","g":"Antes de sair","t":"Malas prontas",
    "x":"Deixe tudo fechado agora. Você volta ao hotel só para pegar e sair.",
    "av":"Se quiser sair à noite antes do voo, o Dedalos abre 24h e fica a 8 min a pé do hotel. Dá para ir às 20:00 e ainda sair às 22:30."},
   {"h":"19:30","k":"jantar","t":"Jantar no hotel ou delivery","x":"Refeição simples antes do aeroporto."},
   {"h":"22:30","k":"via","g":"Transfer","t":"Sooz → GRU",
    "x":"45 min de carro. Estar no Terminal 3 às 23:10.",
    "av":"Transfer ainda não reservado. O check-out formal é 02/12 até 12:00, então o quarto é seu a noite toda."}
 ]},

 {"d":"02","m":"dez","sem":"Qua","c":"São Paulo → Doha","r":"Voo de madrugada e escala em Doha","i":[
   {"h":"02:10","k":"voo","g":"Qatar Airways · WY 6128","t":"Guarulhos → Doha",
    "x":"Terminal 3. Chega Doha 21:40. Qsuite, assento 5K. A350-1000.","cod":"9TNDDB","cl":"Reserva Qatar",
    "av":"Check-in abre às 02:10 do dia 30, ainda em Curitiba. Faça pelo celular só para emitir o cartão de embarque."},
   {"h":"21:40","k":"livre","g":"Escala de 10h25","t":"Noite no Hamad",
    "x":"Tudo abre 24 horas. Al Safwa, a sala de primeira da Qatar, à qual seu QR 1006 dá acesso: quartos de descanso, chuveiro e restaurante à la carte. Se quiser sair da sala: Emporio Armani Ristorante no Concourse B, o melhor café do aeroporto. Harrods Tea Room no duty free, para a sambousa de zaatar e as batatas trufadas. Basta, no Concourse C, para comida catariana de verdade: majboos e chá karak. Fendi Caffè fica dentro do jardim The Orchard, no meio do terminal, e é o lugar mais agradável para passar a madrugada.",
    "av":"Peça hotel de trânsito à Qatar antes de pagar. Se não conseguir, o Oryx Garden Hotel fica no fim do Concourse C, dentro da área de trânsito, com academia e chuveiro. Voando Qatar você costuma ter voucher de refeição de US$ 20 por pessoa: pergunte no balcão de conexão."}
 ]},

 {"d":"03","m":"dez","sem":"Qui","c":"Doha → Dubai","r":"Voo direto em primeira classe. Fim da viagem","i":[
   {"h":"08:05","k":"voo","g":"Qatar Airways · QR 1006","t":"Doha → Dubai",
    "x":"Chega 10:25, Terminal 1. Primeira classe, 2 peças de bagagem.","cod":"GCWJDN · 9TNDDB","cl":"Localizadores",
    "av":"Reemissão sem custo depois da alteração de horário. O trecho por Mascate saiu do bilhete e você chega quase 6h antes do que a mudança tinha imposto."}
 ]},
]

PEND = [
 {"n":"Outubro","t":"Museu do Ipiranga · 01/12",
  "p":"Entrada por horário marcado. Monitorar a abertura do calendário em meados de outubro."},
 {"n":"Outubro","t":"Confirmar local e horário do ENADE · 29/11",
  "p":"O cartão de confirmação sai antes da prova. Cheque o endereço e o horário de fechamento dos portões, e avise a mãe onde encontrar você depois."},
 {"n":"Agora","t":"Código da reserva do Novotel Curitiba",
  "p":"O hotel mudou do Pestana para o Novotel, na Rua Doutor Pedrosa 288. Preencha o código nos dias 24 e 29 e avise a Serra Verde Express do novo endereço do apanhe da Litorina."},
 {"n":"Agora","t":"Chão Batido abre na segunda? · 23/11",
  "p":"O jantar do dia 23 é em Santo Antônio de Lisboa, depois do pôr do sol. Confirme por telefone que a casa abre segunda antes de contar com ela."},
 {"n":"Novembro","t":"Transfer Sooz → GRU · noite de 01/12",
  "p":"Voo 02:10. Sair do hotel 22:30, estar no aeroporto às 23:10."},
 {"n":"Novembro","t":"Reservar os jantares que enchem",
  "p":"El Señor Asador no sábado 21 e Chão Batido na segunda 23, em Florianópolis. Ibérico e Taco El Pancho em Curitiba. Graça Mineira em São Paulo. Por telefone ou WhatsApp, uma semana antes."},
 {"n":"Feito","t":"Seguro da mãe · dia na Argentina",
  "p":"Contratado só para a travessia de 18/11, que é onde ele é exigido. Cobertura doméstica fica por conta do convênio dela."},
]
