# -*- coding: utf-8 -*-
# Dias 11/11 a 22/11

DIAS_A = [
 {"d":"11","m":"nov","sem":"Qua","c":"Dubai → Doha","r":"Dois voos e uma espera longa em Doha","i":[
   {"h":"11:00","k":"voo","g":"Oman Air · WY 604","t":"Dubai → Muscat",
    "x":"Terminal 1. Chega 12:10. Executiva, assento 03A. 2 peças de bagagem.","cod":"GCWJDN","cl":"Localizador"},
   {"mv":"2h40|Conexão|Sem sair do terminal de Muscat|12:10"},
   {"h":"14:50","k":"voo","g":"Oman Air · WY 663","t":"Muscat → Doha",
    "x":"Chega 15:30. Conexão de 2h40 em Muscat.","cod":"GCWJDN","cl":"Localizador"},
   {"mv":"10 min|A pé|Portão de chegada → Lounge Al Mourjan|15:20"},
   {"h":"15:30","k":"livre","g":"Cerca de 10h","t":"Espera em Doha",
    "x":"Lounge Al Mourjan pelo acesso da executiva. Pergunte no balcão da Qatar sobre hotel de trânsito.",
    "av":"Brasileiro entra no Catar sem visto. Dá tempo de jantar na cidade se preferir sair."}
 ]},

 {"d":"12","m":"nov","sem":"Qui","c":"Doha → São Paulo","r":"Chegada, Mercadão e ônibus noturno para Lins","i":[
   {"h":"01:35","k":"voo","g":"Qatar Airways · WY 6029","t":"Doha → Guarulhos",
    "x":"Chega 10:40 no Terminal 3. Qsuite, assento 5K.","cod":"9TNDDB","cl":"Reserva Qatar"},
   {"h":"11:30","k":"via","g":"Transfer · 50 min","t":"GRU Terminal 3 → ibis, na República",
    "x":"Já reservado. Chegada por volta das 12:20. Deixe as malas no hotel antes de sair.",
    "cod":"424878405","cl":"Booking"},
   {"mv":"15 min|Uber|ibis → Mercadão|12:25"},
   {"h":"12:40","k":"passeio","g":"2h","t":"Mercado Municipal",
    "x":"Almoce lá: sanduíche de mortadela no mezanino, no Hocca Bar ou no Bar do Mané, e pastel de bacalhau no Hocca. Depois desça e ande pelos boxes de frutas, que dão prova.",
    "av":"Fecha às 18:00. Leve algum dinheiro, parte dos boxes ainda prefere espécie."},
   {"mv":"15 min|Uber|Mercadão → ibis|14:45"},
   {"h":"15:00","k":"hotel","g":"Check-in","t":"ibis budget SP Centro São João",
    "x":"Av. São João 1140, Centro. Check-in até 23:30. Sem café da manhã.","cod":"6443.654.205 · PIN 2219","cl":"Reserva"},
   {"h":"19:30","k":"jantar","t":"Restaurante do ibis budget",
    "x":"Jantar no próprio hotel antes de sair. Evita procurar lugar no centro à noite carregando mala."},
   {"mv":"20 min|Uber|Hotel → Terminal Barra Funda|21:00"},
   {"h":"22:15","k":"onibus","g":"Reunidas","t":"Barra Funda → Lins",
    "x":"Leito cama, poltrona 55, plataforma 10. Chegue por volta das 21:20, com folga.","cod":"010323567770","cl":"Bilhete"}
 ]},

 {"d":"13","m":"nov","sem":"Sex","c":"Lins","r":"Chegada de madrugada e dia com a família","i":[
   {"h":"05:30","k":"via","g":"Chegada","t":"Rodoviária de Lins",
    "x":"Av. Tiradentes 2401. Sua mãe busca vocês no desembarque."},
   {"mv":"15 min|Carro|Rodoviária de Lins → Parque Alto da Boa Vista|05:45"},
   {"h":"06:00","k":"livre","t":"Casa da família",
    "x":"Vá direto para a casa da sua mãe. Banho, café e descanso antes de o dia começar."},
   {"h":"—","k":"livre","g":"Dia inteiro","t":"Família e cidade",
    "x":"Dia livre com os irmãos e as crianças. Sem nada marcado."},
   {"mv":"10 min|Carro|Casa da família → Cristal Palace|14:50"},
   {"h":"15:00","k":"hotel","g":"Check-in","t":"Cristal Palace Hotel",
    "x":"Rua Luiz Gama 1771. 2 noites, café incluído. Deixe a mala e volte para a família.",
    "cod":"6314.563.781 · PIN 9867","cl":"Reserva",
    "av":"Obra no prédio das 09:00 às 19:00. Como você passa o dia fora, só incomoda se voltar para descansar à tarde."},
   {"h":"19:00","k":"jantar","t":"Em casa, com a mãe","x":"Sem restaurante. Ela cozinha."}
 ]},

 {"d":"14","m":"nov","sem":"Sáb","c":"Lins","r":"Dia livre e a festa de 90 anos da vó Maria","i":[
   {"h":"—","k":"livre","g":"Dia livre","t":"Sem planos","x":"Dia aberto com a família. A festa é só à noite."},
   {"h":"19:30","k":"festa","g":"Compromisso do dia","t":"Festa de 90 anos da vó Maria",
    "x":"O único compromisso da viagem com data que não se remarca. A festa tem buffet, então não há jantar marcado.",
    "av":"Leve a câmera carregada e cartão vazio. É o material mais valioso que você vai trazer da viagem."}
 ]},

 {"d":"15","m":"nov","sem":"Dom","c":"Lins → Bauru → Foz","r":"Manhã com a família e a conexão mais apertada da viagem","i":[
   {"h":"08:00","k":"hotel","g":"Check-out","t":"Cristal Palace",
    "x":"Check-out das 06:00 às 13:00. Saia cedo e deixe as malas na casa da família."},
   {"mv":"10 min|Carro|Cristal Palace → Casa da família|08:05"},
   {"h":"08:15","k":"livre","g":"Manhã e início da tarde","t":"Livre com a família",
    "x":"Despedida sem pressa. Faça a refeição principal aqui, porque em Bauru sobra pouco mais de uma hora."},
   {"mv":"10 min|Carro|Casa da família → Rodoviária de Lins|14:30"},
   {"h":"15:05","k":"onibus","g":"Reunidas","t":"Lins → Bauru",
    "x":"Executivo. Rafa poltrona 3, mãe poltrona 4. Chega 17:20. Chegue por volta das 14:40.",
    "cod":"Rafa 010332443574 · Mãe 010332443908","cl":"Bilhetes"},
   {"h":"17:20","k":"livre","g":"1h55 até o Garcia","t":"Bauru",
    "x":"Sem tempo para sair da rodoviária. Coma algo ali mesmo e fique de olho na plataforma.",
    "av":"É a folga mais curta do roteiro. Se o Reunidas atrasar muito, o Garcia das 19:15 é o único do dia. Plano B: Hotel Saint Martin, a minutos da rodoviária."},
   {"h":"19:15","k":"onibus","g":"Viação Garcia","t":"Bauru → Foz do Iguaçu",
    "x":"Cabine cama. Rafa poltrona 79, mãe poltrona 80. Linha Ribeirão Preto–Foz do Iguaçu.",
    "cod":"Rafa 4378632 · Mãe 4378633","cl":"Bilhetes",
    "av":"A plataforma não vem impressa no bilhete. Confirme no painel ao chegar em Bauru."}
 ]},

 {"d":"16","m":"nov","sem":"Seg","c":"Foz do Iguaçu","r":"Chegada de ônibus e Itaipu à tarde. Dia curto de propósito","i":[
   {"h":"09:25","k":"via","g":"Chegada","t":"Rodoviária de Foz",
    "x":"Desembarque, retirada das malas do bagageiro e táxi ou app. Conte uns 30 min até estar no carro."},
   {"mv":"20 min|Uber|Rodoviária de Foz → Recanto Cataratas|09:55"},
   {"h":"10:15","k":"hotel","g":"Guarda-volumes","t":"Recanto Cataratas Thermas Resort",
    "x":"Av. Costa e Silva 3500. Check-in só às 15:00. Deixe as malas, use as piscinas termais e almoce ali antes de Itaipu.",
    "cod":"5712.155.290 · PIN 6847","cl":"Reserva"},
   {"mv":"25 min|Uber|Recanto Cataratas → Itaipu|14:05"},
   {"h":"14:30","k":"passeio","t":"Itaipu Special Tour",
    "x":"Av. Tancredo Neves 6702. Visita às 15:00, chegue 30 min antes.","cod":"LB28862517","cl":"Ingresso",
    "av":"Nenhum tipo de bolsa é permitido, armário custa R$ 10. Calçado fechado sem salto. Documento com foto. Drones proibidos."},
   {"mv":"20 min|Uber|Itaipu → Monjolo|19:40"},
   {"h":"20:00","k":"jantar","g":"Jantar decidido","t":"Baru Gastronomia",
    "x":"Av. Paraná 3515, Monjolo. Contemporânea, porções generosas. Aberto das 07:00 à meia-noite, todos os dias.",
    "cod":"+55 45 99112-5003","cl":"Telefone"}
 ]},

 {"d":"17","m":"nov","sem":"Ter","c":"Foz do Iguaçu","r":"Manhã livre, Parque das Aves e o pôr do sol","i":[
   {"h":"09:00","k":"livre","g":"Manhã livre","t":"Descanso no Recanto",
    "x":"Termas, piscina e café sem pressa. O dia só começa de verdade às 13:00."},
   {"mv":"20 min|Uber|Recanto Cataratas → Parque das Aves|12:40"},
   {"h":"13:00","k":"passeio","g":"3h","t":"Parque das Aves",
    "x":"Entrada válida das 08:30 às 16:30. Fica em frente ao Parque Nacional.","cod":"LB28862797","cl":"Ingresso"},
   {"mv":"5 min|A pé|Parque das Aves → Centro de Visitantes|16:25"},
   {"h":"16:30","k":"passeio","t":"Pôr do Sol nas Cataratas",
    "x":"Embarque no Centro de Visitantes às 17:00 ou 17:30. Desembarque no Espaço Naipi dá acesso aos elevadores da Garganta do Diabo sem trilha. Brinde com espumante incluso.",
    "cod":"LB30619681","cl":"Ingresso",
    "av":"Retire a pulseira antes, na Sala de Turismo do Centro de Visitantes. Acontece com qualquer clima."},
   {"mv":"20 min|Uber|Espaço Naipi → Recanto Cataratas|19:40"},
   {"h":"20:00","k":"jantar","t":"No Recanto Cataratas",
    "x":"Sem sair de novo. Vocês voltam do pôr do sol já tarde e o restaurante do resort resolve."}
 ]},

 {"d":"18","m":"nov","sem":"Qua","c":"Foz → Argentina","r":"Lado argentino das cataratas. Dia de passaporte","i":[
   {"h":"—","k":"passeio","g":"Dia inteiro","t":"Cataratas Argentinas",
    "x":"Transporte compartilhado, ingresso e taxa de turismo inclusos. O almoço não está incluso: coma nos restaurantes do parque ou leve lanche, porque o dia inteiro é dentro dele.",
    "cod":"Venda 190815","cl":"Reserva",
    "av":"Leve o passaporte e uma cópia do documento da mãe. O horário do apanhe é informado depois das 18:30 do dia anterior. Pós-venda +55 45 99134-1079."},
   {"mv":"40 min|Van|Puerto Iguazú → Recanto Cataratas|17:50"},
   {"h":"18:30","k":"via","g":"Volta","t":"Chegada ao Recanto",
    "x":"Horário aproximado. Dia inteiro em pé, com travessia de fronteira nos dois sentidos."},
   {"h":"20:00","k":"jantar","g":"Decidir no dia","t":"No Recanto ou TropCalia",
    "x":"Se vocês voltarem da Argentina depois das 18:30, jantem no resort mesmo. Se chegarem cedo e com disposição, o TropCalia fica a 15 min e vai até 23:30.",
    "cod":"+55 45 99809-0120","cl":"TropCalia"}
 ]},

 {"d":"19","m":"nov","sem":"Qui","c":"Foz → Florianópolis","r":"Amanhecer nas cataratas, termas e ônibus noturno","i":[
   {"mv":"20 min|Uber|Recanto Cataratas → Parque Nacional|04:40"},
   {"h":"05:00","k":"passeio","g":"Madrugada","t":"Amanhecer nas Cataratas com café",
    "x":"Entrada no parque brasileiro antes da abertura ao público. Café no Porto Canoas.",
    "cod":"Venda 190815","cl":"Reserva",
    "av":"De madrugada há pouco carro rodando. Peça o Uber com antecedência ou combine o táxi na recepção do Recanto na noite anterior."},
   {"mv":"25 min|Uber|Parque Nacional → Recanto Cataratas|11:35"},
   {"h":"12:00","k":"hotel","g":"Check-out","t":"Recanto Cataratas",
    "x":"Deixe as malas na bagageira até a hora do ônibus."},
   {"h":"14:00","k":"livre","g":"Tarde","t":"Termas do Recanto",
    "x":"Lado brasileiro já visto no amanhecer e no pôr do sol. A tarde fica para as piscinas termais antes do ônibus."},
   {"mv":"20 min|Uber|Recanto Cataratas → Rodoviária de Foz|17:20"},
   {"h":"18:15","k":"onibus","g":"Catarinense","t":"Foz → Florianópolis",
    "x":"Embarque das 18:15 às 18:44, saída 18:45. Leito cama, poltronas 61 e 62. Chegue por volta das 17:40.",
    "cod":"Rafa BPE 7012154 · Mãe BPE 7012153","cl":"Bilhetes"}
 ]},

 {"d":"20","m":"nov","sem":"Sex","c":"Florianópolis","r":"Chegada, centro histórico e ponte no fim da tarde","i":[
   {"h":"11:00","k":"via","g":"Chegada","t":"Rodoviária de Florianópolis","x":"Carro até o Novotel, cerca de 15 min."},
   {"mv":"15 min|Uber|Rodoviária de Floripa → Novotel|11:15"},
   {"h":"11:30","k":"hotel","g":"Guarda-volumes","t":"Novotel Florianópolis",
    "x":"Av. Rubens Arruda Ramos 2034, Beira Mar Norte. Deixe as malas, o quarto sai às 15:00.",
    "cod":"6172.585.897 · PIN 3972","cl":"Reserva",
    "av":"Peça early check-in no balcão. Se houver quarto livre, a rede Accor costuma liberar sem cobrar."},
   {"mv":"10 min|Uber|Novotel → Mercado Público|11:50"},
   {"h":"12:00","k":"passeio","g":"1h30","t":"Mercado Público","x":"Almoço ali mesmo, logo na chegada."},
   {"mv":"3 min|A pé|Mercado Público → Praça XV|13:42"},
   {"h":"13:45","k":"passeio","g":"1h","t":"Praça XV e Catedral",
    "x":"A figueira centenária da praça e a catedral ficam lado a lado. Passeio curto e sombreado."},
   {"mv":"20 min|A pé|Praça XV → mirante da ponte|14:40"},
   {"h":"15:00","k":"passeio","g":"1h30","t":"Ponte Hercílio Luz",
    "x":"Fica perto do centro, então aproveite que vocês já estão aqui em vez de voltar depois. O mirante do lado da ilha é o melhor ângulo.",
    "av":"Se alguém estiver cansado, pegue Uber. São 8 min da praça."},
   {"mv":"10 min|Uber|Mirante da ponte → Novotel|16:50"},
   {"h":"17:00","k":"hotel","g":"Check-in","t":"Novotel Florianópolis",
    "x":"Quatro noites, 2 camas de solteiro, café incluído. Banho e descanso antes do jantar."},
   {"mv":"10 min|Uber|Novotel → Praça Getúlio Vargas|19:50"},
   {"h":"20:00","k":"jantar","g":"Jantar decidido","t":"Los Troncos Parrilla",
    "x":"Praça Getúlio Vargas 158, Centro. Parrilla uruguaia, carne no ponto certo. Sexta até 23:00. Reserve, costuma lotar.",
    "cod":"+55 48 99205-3743","cl":"Telefone"}
 ]},

 {"d":"21","m":"nov","sem":"Sáb","c":"Florianópolis","r":"Costa da Lagoa de barco, o vilarejo sem carros","i":[
   {"mv":"25 min|Uber|Novotel → Lagoa da Conceição|09:00"},
   {"h":"09:25","k":"via","g":"Embarque","t":"Centrinho da Lagoa da Conceição",
    "x":"O embarque da Cooperbarco fica na Rua Sen. Ivo D'Aquino 2, na beira da lagoa.",
    "av":"A Cooperbarco só aceita pix, débito ou dinheiro. Cartão de crédito não passa."},
   {"h":"09:45","k":"passeio","g":"Barco · 30 min","t":"Travessia até a Costa da Lagoa",
    "x":"Barco da Cooperbarco atravessando a Lagoa da Conceição. Sente do lado esquerdo para a vista dos morros."},
   {"h":"10:15","k":"passeio","g":"4h","t":"Costa da Lagoa",
    "x":"Vilarejo sem carro nenhum, só trilha e casas na beira d'água. Caminhe pela margem, sente nos restaurantes sobre a água e almoce lá.",
    "av":"Terreno plano na beira, mas com degraus nos trapiches. Sapato fechado ajuda. Sábado o vilarejo inteiro funciona, que é a vantagem de ter trocado o dia."},
   {"h":"14:30","k":"passeio","g":"Barco · 30 min","t":"Volta para a Lagoa da Conceição",
    "x":"Confirme o horário do último barco na chegada. Eles rodam das 08:00 às 20:00, mas com intervalos."},
   {"mv":"25 min|Uber|Lagoa da Conceição → Novotel|15:05"},
   {"h":"15:30","k":"livre","g":"Tarde livre","t":"Volta ao Novotel",
    "x":"Banho e descanso. O dia inteiro foi na água e o jantar é a cinco minutos a pé."},
   {"mv":"5 min|A pé|Novotel → Rua Bocaiúva|19:25"},
   {"h":"19:30","k":"jantar","g":"Jantar decidido","t":"El Señor Asador de Brasa",
    "x":"Rua Bocaiúva 2098, Centro. Carnes na brasa, cordeiro e arroz de pato. Sábado até 23:20, a cinco minutos a pé do hotel.",
    "cod":"+55 48 3113-2088","cl":"Telefone"}
 ]},

 {"d":"22","m":"nov","sem":"Dom","c":"Florianópolis","r":"Dia inteiro no norte da ilha, sem travessia","i":[
   {"mv":"35 min|Uber|Novotel → Jurerê|09:30"},
   {"h":"10:05","k":"passeio","g":"2h30","t":"Praia de Jurerê",
    "x":"Mar calmo e areia plana, boa para caminhar a orla inteira. A parte tradicional, e não Jurerê Internacional, é mais tranquila num domingo."},
   {"mv":"5 min|A pé|Orla → restaurantes da Av. dos Búzios|12:40"},
   {"h":"12:45","k":"jantar","g":"1h30","t":"Almoço em Jurerê",
    "x":"Faça a refeição principal aqui. Tem casa de carne e massa além dos frutos do mar."},
   {"mv":"12 min|Uber|Jurerê → Praia Daniela|14:18"},
   {"h":"14:30","k":"passeio","g":"2h","t":"Praia Daniela",
    "x":"A 12 min dali, ainda mais calma e rasa. Boa para sentar à sombra no fim da tarde."},
   {"mv":"35 min|Uber|Praia Daniela → Novotel|16:55"},
   {"h":"17:30","k":"livre","g":"Volta","t":"Novotel Florianópolis",
    "x":"Tarde livre. Amanhã é o dia mais longo da ilha, com pôr do sol em Santo Antônio e jantar por lá."},
   {"mv":"8 min|Uber|Novotel → Centro|19:52"},
   {"h":"20:00","k":"jantar","g":"Jantar decidido","t":"Trattoria Carbone",
    "x":"Rua Felipe Schmidt 869, Centro. Costela invernale e risoto. Domingo até 23:00, quando quase tudo no centro fecha.",
    "cod":"+55 48 3054-0731","cl":"Telefone"}
 ]},
]
